### ISSUE TITLE
Doesn't install on mac

### ISSUE THREAD

**Issue by martinblampied** [Pin1yin1/pin1yin1#23]
Errno::EPERM: Operation not permitted @ chmod_internal -
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json.rb
An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by fifieldt** [comment]
Hi,

Thanks for the report.

I'm not a mac user, but just looking at the error it seems to be coming from the installation of a particular ruby gem (json) that is a dependency of pin1yin1. Guessing this happened when you ran the 'bundle' command?

It looks like the bundler is trying to install the json gem in a system directory. If this is the desired place (as opposed to wrangling a local install using rvm, chruby etc), does prefixing the command with sudo work?

**Comment by martinblampied** [comment]
Yeah tried that. I believe its because json 1.8 has since been removed, only version I could find was 2.0.

**Comment by fifieldt** [comment]
Thanks. May I ask what version of Ruby you're running?

**Comment by fifieldt** [comment]
Ruby 2.4 and 1.8.3 json compatibility issues detailed here: https://github.com/flori/json/issues/303

**Comment by fifieldt** [comment]
There's a branch at

https://github.com/fifieldt/pin1yin1/tree/ruby-2.4

which should make things work for ruby 2.4/rails 5 that probably fixes the issue. Could you give it a try?

**Comment by martinblampied** [comment]
That worked thanks!
