### ISSUE TITLE
Test and update for unicode 10

### ISSUE THREAD

**Issue by fifieldt** [Pin1yin1/pin1yin1#27]
Pin1yin1.com currently uses unicode 9 data.

Unicode 10 is expected to be released in June 2017.

Beta versions of unihan.zip can already be found at:
ftp://ftp.unicode.org/Public/10.0.0/ucd/

Test pin1yin1 works with unicode 10, make and modifications necessary and update when unicode 10 is released.

**Comment by DanGrayson** [comment]
The current files seem to be version 8.

**Comment by fifieldt** [comment]
Correct you are :) Make that 8-->10, with probable stop at 9 to see the changes there.
