### ISSUE TITLE
'𥚃' causes offset bug

### ISSUE THREAD

**Issue by fifieldt** [Pin1yin1/pin1yin1#29]
Inserting '𥚃' into a sentence causes the pinyin and dictionary lookup to be offset forward in a strange way. See screenshot.

![pin1yin1_bug_2017-06](https://user-images.githubusercontent.com/1287116/27167804-34978b8e-51d5-11e7-91f0-97fb6cd11370.png)

**Comment by fifieldt** [comment]
Looks like special characters to do with emoticons are causing this:
eg
<pre>
     | Unicode character | Oct | Dec | Hex | HTML
� | replacement character | 0177775 | 65533 | 0xFFFD | &#65533;
</pre>
is part of:
🙈

suspect the HTMLencode is replacing single unicode characters with multiple HTML entities.

**Comment by pdg137** [comment]
The UTF-8 representation of this character requires four bytes, which doesn't work with mysql's utf8 character set! We need to upgrade the tables to utf8mb4 for this to work.

**Comment by pdg137** [comment]
I have upgraded the tables and connection to utf8mb4 in the latest migration and also upgraded the server to 18.04 and database to MariaDB. This bug is still present, so I need to write tests to look into it more.

**Comment by pdg137** [comment]
It turned out that there was a Javascript issue with the higher-numbered characters, too. See [this post](https://blog.jonnew.com/posts/poo-dot-length-equals-two) for an explanation. Fixed as of 5572bbf66832a4f68dd44c6885327bf8af0486a0.

**Comment by fifieldt** [comment]
Wow, nice find!
